(defun c:qqs()
	(PROGN
	  (ENTMAKE '((0 . "BLOCK")
		     (8 . "0")
		     (10 0.0 0.0 0.0)
		     (2 . "_NBT_cross")
		     (70 . 2)
		     (1 . "")
		    )
	  )
	  (ENTMAKE '((0 . "LINE")
		     (8 . "0")
		     (67 . 0)
		     (10 0.353553 -0.353553 0.0)
		     (11 -0.353553 0.353553 0.0)
		     (210 0.0 0.0 1.0)
		    )
	  )
	  (ENTMAKE '((0 . "LINE")
		     (8 . "0")
		     (10 -0.353553 -0.353553 0.0)
		     (11 0.353553 0.353553 0.0)
		    )
	  )
	  (ENTMAKE
	    '((0 . "LINE") (8 . "0") (10 0.0 0.0 0.0) (11 -1.0 0.0 0.0))
	  )
	  (ENTMAKE (list '(0 . "ATTRIB")
		 (cons 10 '(1 0 0))
		 (cons 11 '(1 0 0))
		 (cons 40 1)		 
		 (cons 1 "0.1")
		 (cons 3 "0.2")
		 (cons 2  "heigth") ;height
		 '(74 . 2)
		 '(70 . 2)
	   )
	)
	  (ENTMAKE '((0 . "Endblk")))
	)

  	(setq pt(getpoint "Please input the insert point"))
        (entmake (list '(0 . "INSERT") (cons 2 "_NBT_cross") (cons 10 pt)))
)